import { DataSource } from 'typeorm';
import {
  GameItem,
  ItemCategory,
  ItemRarity,
} from '../../../domain/entities/game-item.entity';

interface GameItemSeed {
  name: string;
  description: string;
  category: ItemCategory;
  rarity: ItemRarity;
  requiredFollowers: number;
  engagementBonus: number;
  followersPerHourBonus: number;
  brand?: string;
  model?: string;
  sortOrder: number;
}

const gameItemsSeedData: GameItemSeed[] = [
    {
        name: 'Fiat Palio 1998',
        description: 'Hatch classico de entrada, economico e confiavel.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.COMMON,
        requiredFollowers: 10000,
        engagementBonus: 0.10,
        followersPerHourBonus: 1000,
        brand: 'Fiat',
        model: 'Palio 1998',
        sortOrder: 1,
    },
    {
        name: 'Gol Bolinha',
        description: 'Icone popular brasileiro, manutencao simples e barata.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.COMMON,
        requiredFollowers: 25000,
        engagementBonus: 0.12,
        followersPerHourBonus: 2500,
        brand: 'Volkswagen',
        model: 'Gol Bolinha',
        sortOrder: 2,
    },
    {
        name: 'Golf Sapao',
        description: 'Hatch esportivo de respeito, presenca forte no game.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.COMMON,
        requiredFollowers: 50000,
        engagementBonus: 0.15,
        followersPerHourBonus: 5000,
        brand: 'Volkswagen',
        model: 'Golf Sapao',
        sortOrder: 3,
    },
    {
        name: 'Honda Civic 2008',
        description: 'Seda equilibrado entre conforto, status e performance.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.COMMON,
        requiredFollowers: 75000,
        engagementBonus: 0.18,
        followersPerHourBonus: 7500,
        brand: 'Honda',
        model: 'Civic 2008',
        sortOrder: 4,
    },
    {
        name: 'Hyundai Veloster',
        description: 'Visual esportivo para comecar a chamar atencao.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.RARE,
        requiredFollowers: 100000,
        engagementBonus: 0.20,
        followersPerHourBonus: 10000,
        brand: 'Hyundai',
        model: 'Veloster',
        sortOrder: 5,
    },
    {
        name: 'Volkswagen Jetta GLI',
        description: 'Seda turbo com pegada esportiva e estilo executivo.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.RARE,
        requiredFollowers: 150000,
        engagementBonus: 0.22,
        followersPerHourBonus: 15000,
        brand: 'Volkswagen',
        model: 'Jetta GLI',
        sortOrder: 6,
    },
    {
        name: 'Audi A3 Sedan',
        description: 'Primeiro salto premium com acabamento de luxo.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.RARE,
        requiredFollowers: 200000,
        engagementBonus: 0.25,
        followersPerHourBonus: 20000,
        brand: 'Audi',
        model: 'A3 Sedan',
        sortOrder: 7,
    },
    {
        name: 'Mercedes A45 AMG',
        description: 'Compacto extremo com desempenho de pista.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.RARE,
        requiredFollowers: 250000,
        engagementBonus: 0.28,
        followersPerHourBonus: 25000,
        brand: 'Mercedes-Benz',
        model: 'A45 AMG',
        sortOrder: 8,
    },
    {
        name: 'BMW X1',
        description: 'SUV premium versatil para elevar o padrao do perfil.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.RARE,
        requiredFollowers: 300000,
        engagementBonus: 0.30,
        followersPerHourBonus: 30000,
        brand: 'BMW',
        model: 'X1',
        sortOrder: 9,
    },
    {
        name: 'BMW 320i',
        description: 'Seda alemao classico, combinacao de luxo e presenca.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.RARE,
        requiredFollowers: 350000,
        engagementBonus: 0.32,
        followersPerHourBonus: 35000,
        brand: 'BMW',
        model: '320i',
        sortOrder: 10,
    },
    {
        name: 'BMW M3',
        description: 'Esportivo iconico com status alto na vitrine.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.EPIC,
        requiredFollowers: 400000,
        engagementBonus: 0.35,
        followersPerHourBonus: 40000,
        brand: 'BMW',
        model: 'M3',
        sortOrder: 11,
    },
    {
        name: 'Audi RS3',
        description: 'Compacto brutal com performance de supercarro.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.EPIC,
        requiredFollowers: 425000,
        engagementBonus: 0.38,
        followersPerHourBonus: 42500,
        brand: 'Audi',
        model: 'RS3',
        sortOrder: 12,
    },
    {
        name: 'Chevrolet Camaro SS',
        description: 'Muscle car americano com visual agressivo.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.EPIC,
        requiredFollowers: 450000,
        engagementBonus: 0.40,
        followersPerHourBonus: 45000,
        brand: 'Chevrolet',
        model: 'Camaro SS',
        sortOrder: 13,
    },
    {
        name: 'Ford Mustang GT',
        description: 'Lenda dos esportivos, potencia e carisma.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.EPIC,
        requiredFollowers: 500000,
        engagementBonus: 0.42,
        followersPerHourBonus: 50000,
        brand: 'Ford',
        model: 'Mustang GT',
        sortOrder: 14,
    },
    {
        name: 'Porsche Macan GTS',
        description: 'SUV esportivo premium com dirigibilidade refinada.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.EPIC,
        requiredFollowers: 600000,
        engagementBonus: 0.45,
        followersPerHourBonus: 60000,
        brand: 'Porsche',
        model: 'Macan GTS',
        sortOrder: 15,
    },
    {
        name: 'Range Rover Evoque',
        description: 'SUV urbano de luxo com forte apelo visual.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.EPIC,
        requiredFollowers: 750000,
        engagementBonus: 0.48,
        followersPerHourBonus: 75000,
        brand: 'Land Rover',
        model: 'Range Rover Evoque',
        sortOrder: 16,
    },
    {
        name: 'Range Rover Velar',
        description: 'Design sofisticado e presenca de alto padrao.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.EPIC,
        requiredFollowers: 1000000,
        engagementBonus: 0.50,
        followersPerHourBonus: 100000,
        brand: 'Land Rover',
        model: 'Range Rover Velar',
        sortOrder: 17,
    },
    {
        name: 'Porsche Boxster Spyder',
        description: 'Conversivel esportivo para conteudo de impacto.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.EPIC,
        requiredFollowers: 1500000,
        engagementBonus: 0.52,
        followersPerHourBonus: 150000,
        brand: 'Porsche',
        model: 'Boxster Spyder',
        sortOrder: 18,
    },
    {
        name: 'Porsche 911 Carrera S',
        description: 'Icone atemporal da Porsche com performance precisa.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.EPIC,
        requiredFollowers: 1750000,
        engagementBonus: 0.55,
        followersPerHourBonus: 175000,
        brand: 'Porsche',
        model: '911 Carrera S',
        sortOrder: 19,
    },
    {
        name: 'Porsche Panamera Turbo',
        description: 'Seda de luxo com alma de superesportivo.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.LEGENDARY,
        requiredFollowers: 2500000,
        engagementBonus: 0.58,
        followersPerHourBonus: 250000,
        brand: 'Porsche',
        model: 'Panamera Turbo',
        sortOrder: 20,
    },
    {
        name: 'Porsche GT3 RS',
        description: 'Foco total em pista com precisao extrema.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.LEGENDARY,
        requiredFollowers: 2750000,
        engagementBonus: 0.60,
        followersPerHourBonus: 275000,
        brand: 'Porsche',
        model: '911 GT3 RS',
        sortOrder: 21,
    },
    {
        name: 'Mercedes AMG GLE 63 Coupe',
        description: 'SUV coupe de alta performance e luxo esportivo.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.LEGENDARY,
        requiredFollowers: 3000000,
        engagementBonus: 0.63,
        followersPerHourBonus: 300000,
        brand: 'Mercedes-AMG',
        model: 'GLE 63 Coupe',
        sortOrder: 22,
    },
    {
        name: 'Mercedes AMG G63',
        description: 'Presenca imponente com status de celebridade.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.LEGENDARY,
        requiredFollowers: 4000000,
        engagementBonus: 0.65,
        followersPerHourBonus: 400000,
        brand: 'Mercedes-AMG',
        model: 'G63',
        sortOrder: 23,
    },
    {
        name: 'Lamborghini Urus',
        description: 'Super SUV para conteudo de alto engajamento.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.LEGENDARY,
        requiredFollowers: 5000000,
        engagementBonus: 0.68,
        followersPerHourBonus: 500000,
        brand: 'Lamborghini',
        model: 'Urus',
        sortOrder: 24,
    },
    {
        name: 'Lamborghini Huracan',
        description: 'Superesportivo italiano com visual marcante.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.LEGENDARY,
        requiredFollowers: 7500000,
        engagementBonus: 0.70,
        followersPerHourBonus: 750000,
        brand: 'Lamborghini',
        model: 'Huracan',
        sortOrder: 25,
    },
    {
        name: 'McLaren 720S',
        description: 'Aceleracao brutal e design aerodinamico extremo.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.LEGENDARY,
        requiredFollowers: 9000000,
        engagementBonus: 0.73,
        followersPerHourBonus: 900000,
        brand: 'McLaren',
        model: '720S',
        sortOrder: 26,
    },
    {
        name: 'Ferrari SF90 Stradale',
        description: 'Ferrari hibrida de referencia em tecnologia.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.LEGENDARY,
        requiredFollowers: 12500000,
        engagementBonus: 0.75,
        followersPerHourBonus: 1250000,
        brand: 'Ferrari',
        model: 'SF90 Stradale',
        sortOrder: 27,
    },
    {
        name: 'Ferrari 488 Pista',
        description: 'Pacote de pista com performance e exclusividade.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.LEGENDARY,
        requiredFollowers: 15000000,
        engagementBonus: 0.78,
        followersPerHourBonus: 1500000,
        brand: 'Ferrari',
        model: '488 Pista',
        sortOrder: 28,
    },
    {
        name: 'Rolls-Royce Cullinan',
        description: 'Luxo maximo em forma de SUV ultra premium.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.LEGENDARY,
        requiredFollowers: 20000000,
        engagementBonus: 0.80,
        followersPerHourBonus: 2000000,
        brand: 'Rolls-Royce',
        model: 'Cullinan',
        sortOrder: 29,
    },
    {
        name: 'Ferrari Purosangue',
        description: 'SUV Ferrari raro, desejado e altamente exclusivo.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.LEGENDARY,
        requiredFollowers: 25000000,
        engagementBonus: 0.85,
        followersPerHourBonus: 2500000,
        brand: 'Ferrari',
        model: 'Purosangue',
        sortOrder: 30,
    },
    {
        name: 'Lamborghini Aventador SVJ',
        description: 'Topo absoluto da colecao, presenca lendaria.',
        category: ItemCategory.VEHICLE_CAR,
        rarity: ItemRarity.LEGENDARY,
        requiredFollowers: 30000000,
        engagementBonus: 0.90,
        followersPerHourBonus: 3000000,
        brand: 'Lamborghini',
        model: 'Aventador SVJ',
        sortOrder: 31,
    },

    {
        name: 'Honda CG 125cc',
        description: 'A moto de entrada clÃ¡ssica para iniciar na pista.',
        category: ItemCategory.VEHICLE_MOTORCYCLE,
        rarity: ItemRarity.COMMON,
        requiredFollowers: 10000,
        engagementBonus: 0.10,
        followersPerHourBonus: 1000,
        brand: 'Honda',
        model: 'CG 125cc 2005',
        sortOrder: 1,
    },
    {
        name: 'Yamaha XJ6 600cc',
        description: 'Naked equilibrada com bom desempenho urbano.',
        category: ItemCategory.VEHICLE_MOTORCYCLE,
        rarity: ItemRarity.COMMON,
        requiredFollowers: 25000,
        engagementBonus: 0.12,
        followersPerHourBonus: 2500,
        brand: 'Yamaha',
        model: 'XJ6 600cc 2012',
        sortOrder: 2,
    },
    {
        name: 'Honda Hornet 600cc',
        description: 'Modelo icÃ´nico com pegada esportiva e agressiva.',
        category: ItemCategory.VEHICLE_MOTORCYCLE,
        rarity: ItemRarity.COMMON,
        requiredFollowers: 50000,
        engagementBonus: 0.15,
        followersPerHourBonus: 5000,
        brand: 'Honda',
        model: 'Hornet 600cc 2010',
        sortOrder: 3,
    },
    {
        name: 'Honda CB 500X',
        description: 'VersÃ¡til para cidade e viagem com visual aventureiro.',
        category: ItemCategory.VEHICLE_MOTORCYCLE,
        rarity: ItemRarity.COMMON,
        requiredFollowers: 75000,
        engagementBonus: 0.18,
        followersPerHourBonus: 7500,
        brand: 'Honda',
        model: 'CB 500X 2021',
        sortOrder: 4,
    },
    {
        name: 'Yamaha MT-09',
        description: 'Torque forte e visual moderno da linha Master of Torque.',
        category: ItemCategory.VEHICLE_MOTORCYCLE,
        rarity: ItemRarity.RARE,
        requiredFollowers: 100000,
        engagementBonus: 0.20,
        followersPerHourBonus: 10000,
        brand: 'Yamaha',
        model: 'MT-09 2022',
        sortOrder: 5,
    },
    {
        name: 'Kawasaki Z900',
        description: 'Naked de alta cilindrada com excelente relaÃ§Ã£o peso-potÃªncia.',
        category: ItemCategory.VEHICLE_MOTORCYCLE,
        rarity: ItemRarity.RARE,
        requiredFollowers: 150000,
        engagementBonus: 0.22,
        followersPerHourBonus: 15000,
        brand: 'Kawasaki',
        model: 'Z900 2022',
        sortOrder: 6,
    },
    {
        name: 'Honda CB 1000R',
        description: 'Neo sports cafÃ© com desempenho de litro e estilo premium.',
        category: ItemCategory.VEHICLE_MOTORCYCLE,
        rarity: ItemRarity.RARE,
        requiredFollowers: 200000,
        engagementBonus: 0.25,
        followersPerHourBonus: 20000,
        brand: 'Honda',
        model: 'CB 1000R 2023',
        sortOrder: 7,
    },
    {
        name: 'Triumph Speed Triple RS',
        description: 'Naked britÃ¢nica de alta performance com eletrÃ´nica avanÃ§ada.',
        category: ItemCategory.VEHICLE_MOTORCYCLE,
        rarity: ItemRarity.RARE,
        requiredFollowers: 250000,
        engagementBonus: 0.28,
        followersPerHourBonus: 25000,
        brand: 'Triumph',
        model: 'Speed Triple RS 2022',
        sortOrder: 8,
    },
    {
        name: 'Honda Africa Twin',
        description: 'Big trail consagrada para aventura on-road e off-road.',
        category: ItemCategory.VEHICLE_MOTORCYCLE,
        rarity: ItemRarity.EPIC,
        requiredFollowers: 300000,
        engagementBonus: 0.30,
        followersPerHourBonus: 30000,
        brand: 'Honda',
        model: 'Africa Twin 2023',
        sortOrder: 9,
    },
    {
        name: 'Harley-Davidson Fat Boy',
        description: 'Custom clÃ¡ssica com presenÃ§a marcante e visual robusto.',
        category: ItemCategory.VEHICLE_MOTORCYCLE,
        rarity: ItemRarity.EPIC,
        requiredFollowers: 350000,
        engagementBonus: 0.32,
        followersPerHourBonus: 35000,
        brand: 'Harley-Davidson',
        model: 'Fat Boy 2021',
        sortOrder: 10,
    },
    {
        name: 'Kawasaki Ninja ZX-10R',
        description: 'Superbike de pista com DNA de competiÃ§Ã£o.',
        category: ItemCategory.VEHICLE_MOTORCYCLE,
        rarity: ItemRarity.EPIC,
        requiredFollowers: 400000,
        engagementBonus: 0.35,
        followersPerHourBonus: 40000,
        brand: 'Kawasaki',
        model: 'Ninja ZX-10R 2023',
        sortOrder: 11,
    },
    {
        name: 'Ducati Streetfighter V4',
        description: 'Naked extrema com tecnologia e motor derivado da Panigale.',
        category: ItemCategory.VEHICLE_MOTORCYCLE,
        rarity: ItemRarity.EPIC,
        requiredFollowers: 500000,
        engagementBonus: 0.40,
        followersPerHourBonus: 50000,
        brand: 'Ducati',
        model: 'Streetfighter V4 2022',
        sortOrder: 12,
    },
    {
        name: 'Ducati Panigale V4',
        description: 'ReferÃªncia em desempenho para uso esportivo de alto nÃ­vel.',
        category: ItemCategory.VEHICLE_MOTORCYCLE,
        rarity: ItemRarity.LEGENDARY,
        requiredFollowers: 600000,
        engagementBonus: 0.45,
        followersPerHourBonus: 60000,
        brand: 'Ducati',
        model: 'Panigale V4 2023',
        sortOrder: 13,
    },
    {
        name: 'BMW S1000 RR',
        description: 'Superbike alemÃ£ com pacote eletrÃ´nico completo de corrida.',
        category: ItemCategory.VEHICLE_MOTORCYCLE,
        rarity: ItemRarity.LEGENDARY,
        requiredFollowers: 750000,
        engagementBonus: 0.50,
        followersPerHourBonus: 75000,
        brand: 'BMW',
        model: 'S1000 RR 2023',
        sortOrder: 14,
    },
    {
        name: 'Kawasaki H2R',
        description: 'Hiperesportiva extrema, topo absoluto de performance.',
        category: ItemCategory.VEHICLE_MOTORCYCLE,
        rarity: ItemRarity.LEGENDARY,
        requiredFollowers: 1000000,
        engagementBonus: 0.60,
        followersPerHourBonus: 100000,
        brand: 'Kawasaki',
        model: 'H2R 2023',
        sortOrder: 15,
    },
    {
        name: 'Camiseta BÃ¡sica',
        description: 'Simples, mas funcional. Todo mundo tem uma.',
        category: ItemCategory.CLOTHING_SHIRT,
        rarity: ItemRarity.COMMON,
        requiredFollowers: 0,
        engagementBonus: 0.005,
        followersPerHourBonus: 2,
        sortOrder: 1,
    },
    {
        name: 'Camiseta Streetwear',
        description: 'Estilo urbano. Marca presenÃ§a.',
        category: ItemCategory.CLOTHING_SHIRT,
        rarity: ItemRarity.COMMON,
        requiredFollowers: 3000,
        engagementBonus: 0.01,
        followersPerHourBonus: 5,
        sortOrder: 2,
    },
    {
        name: 'Camiseta Grife',
        description: 'Marca de luxo. Os seguidores percebem.',
        category: ItemCategory.CLOTHING_SHIRT,
        rarity: ItemRarity.RARE,
        requiredFollowers: 100000,
        engagementBonus: 0.03,
        followersPerHourBonus: 15,
        sortOrder: 3,
    },
    {
        name: 'Camiseta Exclusiva',
        description: 'EdiÃ§Ã£o limitada. Poucos tÃªm acesso.',
        category: ItemCategory.CLOTHING_SHIRT,
        rarity: ItemRarity.EPIC,
        requiredFollowers: 1000000,
        engagementBonus: 0.05,
        followersPerHourBonus: 40,
        sortOrder: 4,
    },
    {
        name: 'Bermuda BÃ¡sica',
        description: 'ConfortÃ¡vel e casual.',
        category: ItemCategory.CLOTHING_SHORTS,
        rarity: ItemRarity.COMMON,
        requiredFollowers: 0,
        engagementBonus: 0.005,
        followersPerHourBonus: 2,
        sortOrder: 1,
    },
    {
        name: 'Bermuda Cargo',
        description: 'Estilo funcional com bolsos extras.',
        category: ItemCategory.CLOTHING_SHORTS,
        rarity: ItemRarity.COMMON,
        requiredFollowers: 3000,
        engagementBonus: 0.01,
        followersPerHourBonus: 5,
        sortOrder: 2,
    },
    {
        name: 'Bermuda Grife',
        description: 'Short premium de marca.',
        category: ItemCategory.CLOTHING_SHORTS,
        rarity: ItemRarity.RARE,
        requiredFollowers: 100000,
        engagementBonus: 0.03,
        followersPerHourBonus: 15,
        sortOrder: 3,
    },
    {
        name: 'Jaqueta Jeans',
        description: 'ClÃ¡ssica e versÃ¡til.',
        category: ItemCategory.CLOTHING_JACKET,
        rarity: ItemRarity.COMMON,
        requiredFollowers: 2000,
        engagementBonus: 0.008,
        followersPerHourBonus: 3,
        sortOrder: 1,
    },
    {
        name: 'Jaqueta de Couro',
        description: 'Estilo rebelde. Perfeita pra foto.',
        category: ItemCategory.CLOTHING_JACKET,
        rarity: ItemRarity.RARE,
        requiredFollowers: 75000,
        engagementBonus: 0.03,
        followersPerHourBonus: 18,
        sortOrder: 2,
    },
    {
        name: 'Jaqueta Puffer Grife',
        description: 'Marca de luxo. Visual diferenciado.',
        category: ItemCategory.CLOTHING_JACKET,
        rarity: ItemRarity.EPIC,
        requiredFollowers: 500000,
        engagementBonus: 0.05,
        followersPerHourBonus: 45,
        sortOrder: 3,
    },
    {
        name: 'CalÃ§a Jeans BÃ¡sica',
        description: 'O bÃ¡sico que funciona.',
        category: ItemCategory.CLOTHING_PANTS,
        rarity: ItemRarity.COMMON,
        requiredFollowers: 0,
        engagementBonus: 0.005,
        followersPerHourBonus: 2,
        sortOrder: 1,
    },
    {
        name: 'CalÃ§a Jogger',
        description: 'Conforto com estilo.',
        category: ItemCategory.CLOTHING_PANTS,
        rarity: ItemRarity.COMMON,
        requiredFollowers: 5000,
        engagementBonus: 0.01,
        followersPerHourBonus: 5,
        sortOrder: 2,
    },
    {
        name: 'CalÃ§a Cargo Premium',
        description: 'Streetwear de respeito.',
        category: ItemCategory.CLOTHING_PANTS,
        rarity: ItemRarity.RARE,
        requiredFollowers: 150000,
        engagementBonus: 0.03,
        followersPerHourBonus: 20,
        sortOrder: 3,
    },
    {
        name: 'CalÃ§a Grife Exclusiva',
        description: 'SÃ³ pra quem pode. Luxo puro.',
        category: ItemCategory.CLOTHING_PANTS,
        rarity: ItemRarity.EPIC,
        requiredFollowers: 2000000,
        engagementBonus: 0.06,
        followersPerHourBonus: 55,
        sortOrder: 4,
    },
    {
        name: 'Quarto Simples',
        description: 'Um quartinho bÃ¡sico. Todo mundo comeÃ§a assim.',
        category: ItemCategory.SCENARIO,
        rarity: ItemRarity.COMMON,
        requiredFollowers: 0,
        engagementBonus: 0.005,
        followersPerHourBonus: 3,
        sortOrder: 1,
    },
    {
        name: 'EstÃºdio Caseiro',
        description: 'Setup bÃ¡sico de gravaÃ§Ã£o. JÃ¡ dÃ¡ pra comeÃ§ar.',
        category: ItemCategory.SCENARIO,
        rarity: ItemRarity.COMMON,
        requiredFollowers: 10000,
        engagementBonus: 0.02,
        followersPerHourBonus: 10,
        sortOrder: 2,
    },
    {
        name: 'Apartamento Moderno',
        description: 'Sala bem decorada. Os seguidores vÃ£o notar.',
        category: ItemCategory.SCENARIO,
        rarity: ItemRarity.RARE,
        requiredFollowers: 100000,
        engagementBonus: 0.04,
        followersPerHourBonus: 30,
        sortOrder: 3,
    },
    {
        name: 'Cobertura de Luxo',
        description: 'Vista da cidade. PadrÃ£o influencer de verdade.',
        category: ItemCategory.SCENARIO,
        rarity: ItemRarity.EPIC,
        requiredFollowers: 1000000,
        engagementBonus: 0.06,
        followersPerHourBonus: 60,
        sortOrder: 4,
    },
    {
        name: 'MansÃ£o',
        description: 'Casa dos sonhos. Piscina, garagem, estÃºdio. VocÃª chegou lÃ¡.',
        category: ItemCategory.SCENARIO,
        rarity: ItemRarity.LEGENDARY,
        requiredFollowers: 5000000,
        engagementBonus: 0.10,
        followersPerHourBonus: 120,
        sortOrder: 5,
    },
    {
        name: 'Ilha Privada',
        description: 'Seu prÃ³prio paraÃ­so. SÃ³ os maiores da internet.',
        category: ItemCategory.SCENARIO,
        rarity: ItemRarity.LEGENDARY,
        requiredFollowers: 20000000,
        engagementBonus: 0.15,
        followersPerHourBonus: 300,
        sortOrder: 6,
    },
];

export async function seedGameItems(dataSource: DataSource): Promise<void> {
  const gameItemRepository = dataSource.getRepository(GameItem);

  for (const itemData of gameItemsSeedData) {
    const existing = await gameItemRepository.findOne({
      where: { name: itemData.name, category: itemData.category },
    });

    if (existing) {
      await gameItemRepository.update(existing.id, {
        description: itemData.description,
        rarity: itemData.rarity,
        requiredFollowers: itemData.requiredFollowers,
        engagementBonus: itemData.engagementBonus,
        followersPerHourBonus: itemData.followersPerHourBonus,
        brand: itemData.brand || undefined,
        model: itemData.model || undefined,
        sortOrder: itemData.sortOrder,
      });
      console.log(`Item "${itemData.name}" (${itemData.category}) updated`);
    } else {
      const item = gameItemRepository.create({
        name: itemData.name,
        description: itemData.description,
        category: itemData.category,
        rarity: itemData.rarity,
        requiredFollowers: itemData.requiredFollowers,
        engagementBonus: itemData.engagementBonus,
        followersPerHourBonus: itemData.followersPerHourBonus,
        brand: itemData.brand,
        model: itemData.model,
        sortOrder: itemData.sortOrder,
        isActive: true,
      } as Partial<GameItem>);
      await gameItemRepository.save(item);
      console.log(`Item "${itemData.name}" (${itemData.category}) created`);
    }
  }

  console.log('Game items seed completed!');
}

